package com.qizaodian.mybatis.mapper;

import com.qizaodian.mybatis.entity.ArticleInfo;
import com.qizaodian.mybatis.entity.ArticleInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int countByExample(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int deleteByExample(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int insert(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int insertSelective(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    List<ArticleInfo> selectByExampleWithBLOBs(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    List<ArticleInfo> selectByExample(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    ArticleInfo selectByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") ArticleInfo record, @Param("example") ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ArticleInfo record, @Param("example") ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int updateByExample(@Param("record") ArticleInfo record, @Param("example") ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int updateByPrimaryKeyWithBLOBs(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Nov 17 09:55:21 GMT+08:00 2016
     */
    int updateByPrimaryKey(ArticleInfo record);
}